CREATE TABLE "TRADE_HISTORY" (
  "EXCHANGE" VARCHAR(15) NOT NULL,
  "SYMBOL" VARCHAR(15) NOT NULL,
  "TRADE_ID" VARCHAR(15) NOT NULL,
  "TIME" TIMESTAMP NOT NULL,
  "PRICE" NUMERIC(15,5) NOT NULL,
  "QUANTITY" NUMERIC(20,10) NOT NULL,
  "TRADE_TYPE" CHAR(1) NOT NULL,
  PRIMARY KEY ("EXCHANGE", "SYMBOL", "TRADE_ID")
);
CREATE INDEX "TRADE_HISTORY_IDX" ON "TRADE_HISTORY"("EXCHANGE", "SYMBOL", "TIME");

CREATE TABLE "POSITIONS" (
  "ID" SERIAL PRIMARY KEY,
  "ACTOR_ID" VARCHAR(20) NOT NULL,
  "QUANTITY" NUMERIC(20,10) NOT NULL,
  "POSITION_TYPE" CHAR(1) NOT NULL,
  "POSITION_STATUS" CHAR(2) NOT NULL,
  "PENDING_ORDER_ID" INT,
  "OPEN_AT" TIMESTAMP,
  "OPEN_PRICE" NUMERIC(15,5),
  "CLOSE_AT" TIMESTAMP,
  "CLOSE_PRICE" NUMERIC(15,5)
);

CREATE INDEX "POSITIONS_ACTOR_IDX" ON "POSITIONS"("ACTOR_ID");