CREATE TABLE "TRADE_HISTORY" (
  "SYMBOL" VARCHAR(10) NOT NULL,
  "TIME" TIMESTAMP NOT NULL,
  "PRICE" NUMERIC(15,5) NOT NULL,
  "QUANTITY" NUMERIC(20,10) NOT NULL
);

CREATE INDEX "TRADE_HISTORY_IDX" ON "TRADE_HISTORY"("SYMBOL", "TIME");

CREATE TABLE "INDICATORS"